[package]
name = "serve"
version = "0.1.3"
authors = ["Xavier Stevens"]

[dependencies]
clap = "2"
itertools = "^0.8"
log = "^0.4"
rocket = { version = "^0.4", features = ["tls"] }
rocket_codegen = "^0.4"
time = "^0.1"
