[package]
name = "serve"
version = "0.2.0"
authors = ["Xavier Stevens"]
edition = "2018"

[dependencies]
clap = "^2.33"
itertools = "^0.10"
log = "^0.4"
rocket = { version = "0.5.0-rc.1", features = ["tls"] }
rocket_codegen = "0.5.0-rc.1"
chrono = "^0.4"
