[package]
name = "serve"
version = "0.3.0"
authors = ["Xavier Stevens"]
edition = "2018"

[dependencies]
clap = "^2.34"
itertools = "^0.13"
log = "^0.4"
rocket = { version = "0.5.1", features = ["tls"] }
rocket_codegen = "0.5.1"
chrono = "^0.4"
serde = "^1.0"
serde_json = "^1.0"
